#!/usr/bin/env python3
"""Generate svf_control's tables (65 even-knob entries each; the handler
interpolates odd knobs) and the tanh table NFX-SV and NFX-4P share.

  tables.inc   svf_cutoff, svf_damping, svf_time, svf_depth, svf_attack
  TANH         tanh(8 m), m = 0..1 in 1,024 intervals: 1,025 Q23 words for internal X

    python3 generate_tables.py           # rewrite tables.inc
    python3 generate_tables.py --check   # fail if tables.inc is stale
"""
import argparse
import math
from pathlib import Path

Q = 1 << 23
HERE = Path(__file__).resolve().parent
TANH = [round(Q * math.tanh(8 * i / 1024)) for i in range(1025)]
TANH_ADDRESS = 0x280            # inside the free internal X gap 0x257-0x6FF


def stage_samples(k):           # ATK/DEC: 1 ms .. 10 s, squared knob curve
    return 44100 * .001 * (1 + 99 * max(0, k - 1) / 126) ** 2


TABLES = {
    # FREQ: SV cutoff word, 0.001 + 2.25 c^4 (uSVF); NFX-4P uses 2x this as its dt
    'svf_cutoff': lambda k: round(Q * min(1.125, (.001 + 2.25 * (k / 127) ** 4) / 2) / 2),
    # RESO (SV): damping 0.9 .. 0.001
    'svf_damping': lambda k: round(Q * max(.001, min(.9, 1 - 1.475 * math.log(1 + k / 127)))),
    # DEC: exponential discharge coefficient to -96 dB
    'svf_time': lambda k: max(1, min(Q - 1, round(Q * -math.expm1(-math.log(65536) / stage_samples(k))))),
    # ENVA: bipolar depth, 64 neutral
    'svf_depth': lambda k: 0 if k == 64 else (-1 if k < 64 else 1) * round(
        (64 if k < 64 else 63) * 73728 * math.expm1(4 * abs(k - 64) / (64 if k < 64 else 63)) / math.expm1(4)),
    # ATK: charge coefficient (to 2x full scale) * 2^31; the handler splits off the scale
    'svf_attack': lambda k: max(1, round((1 << 31) * -math.expm1(-math.log(2) / stage_samples(k)))),
}


def content():
    out = '| GENERATED by generate_tables.py: 65 entries per knob (knobs 0, 2, .. 126, 127).\n'
    for name, fn in TABLES.items():
        out += f'{name}:\n' + ''.join(f'        .long {fn(min(127, 2 * i))}\n' for i in range(65))
    return out


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    path = HERE / 'tables.inc'
    if a.check:
        if path.read_text() != content():
            raise SystemExit('tables.inc is stale: run generate_tables.py')
    else:
        path.write_text(content())
