; GND-SW: PolyBLEP saw, MIDI pitch; stock GND-SN ramp and amplitude envelopes.
; Cycle-optimized. GENERATED by generate_kernel.py from reference.s: edit those.
        include "sdk.inc"
        org p:SDK_BANK
machine_init:
        rts
machine_update:
        move    #>$7ffff8,x0
        move    x0,y:(r6+$a)
        move    x0,y:(r6+$6)
        move    #$0,x0
        move    x0,y:(r6+$9)
        move    x0,y:(r6+$7)
        move    x0,y:(r6+$8)
        rts
machine_render:
        move #0,r4
        move #31,m4
; Stock ramp contribution converted to a 2^23-cycle phase increment (x4).
        move y:(r6+$3),y0
        move y:(r6+$6),y1
        mpy y1,y0,a
        asl #2,a,a
        move y:(r6+$1),x0
        add x0,a
        move #>$3fffff,x0
        cmp x0,a
        jle step_ready
        move x0,a
step_ready:
        move a1,n0
        move y:(r6+$4),y0
        mpy y1,y0,b
        move b,y:(r6+$6)
        move y:(r6+$7),r1
; ---- Fast oscillator: A = phase, X0 = step, X1 = -Q, Y0 = phase mask (copy in N3),
; ---- Y1 = K. The edge subroutine saves the phase in R1.
        move n0,a
        tst a
        jlt generic                   ; negative step: reference loop
        move #>$400000,a              ; K = Q - 2*step (positive, below Q)
        asl a
        move n0,x0
        sub x0,a
        sub x0,a
        move a1,y1
        move a1,n5
        move #>$800000,x1
        move #>$7fffff,y0
        move y0,n3
        move r1,a
        do #32,fast_osc_end
        tfr a,b
        asl b
        add x1,b                      ; raw = 2p - Q
        cmpm y1,b
        jsgt edge_sample              ; |raw| > K: PolyBLEP edge (or wrap at p = 0)
        asr #2,b,b
        add x0,a        b,x:(r4)+
        and y0,a
 fast_osc_end:
        move a1,r1
        jmp osc_end
; ---- PolyBLEP edge subroutine. In: A = phase p, B = raw, X0 = step, X1 = -Q.
; The sign of raw selects the side: raw < 0 is the left edge (p < step), raw > 0
; the right edge (Q - p < step). DIV numerators and the squared correction are
; formed with the reference's exact accumulator values.
 edge_sample:
        move a1,r1
        tst b
        jlt e_left
        add x0,a                      ; right: p + step - Q = step - (Q - p)
        add x1,a
        andi #$fe,ccr
        rep #24
        div x0,a
        move a0,y0
        mpy y0,y0,a
        move a1,a
        sub a,b
        move n3,y0
        move r1,a
        rts
 e_left:
        tst a
        jeq e_wrap                    ; p = 0: the wrap sample itself outputs zero
        neg a                         ; left: step - p
        add x0,a
        andi #$fe,ccr
        rep #24
        div x0,a
        move a0,y0
        mpy y0,y0,a
        move a1,a
        add a,b
        move n3,y0
        move r1,a
        rts
 e_wrap:
        clr b
        rts
; ---- Reference oscillator loop, verbatim ---------------------------------------
 generic:
        do #32,g_osc_end
; Phase is unsigned 0..7fffff. Raw saw = 2*phase - 800000.
        move r1,b
        asl b
        move #>$800000,x1
        add x1,b
        move r1,a
        move n0,x0
        cmp x0,a
        jlt g_left_edge
; Distance to the next wrap is positive here (phase >= step).
        move #>$7fffff,a
        move r1,x1
        sub x1,a
        add #1,a
        cmp x0,a
        jge g_raw_sample
        move a1,x1
        move #1,n1
        jmp g_edge
g_left_edge:
        tst a
        jeq g_wrap_sample
        move a1,x1
        move #0,n1
g_edge:
; u=(step-distance)/step in Q23; DIV requires |numerator|<denominator.
        move x0,a
        sub x1,a
        andi #$fe,ccr
        rep #24
        div x0,a
        move a0,y0
        mpy y0,y0,a
        move a1,y1
        move n1,a
        tst a
        move y1,a
        jeq g_add_correction
        sub a,b
        jmp g_raw_sample
g_add_correction:
        add a,b
g_raw_sample:
        move b,a
        jmp g_store_sample
g_wrap_sample:
        clr a
g_store_sample:
; Match GND-SN's oscillator headroom and native double-word envelope.
        asr #2,a,a
        move a,x:(r4)+
        move r1,a
        move n0,x0
        add x0,a
        and #$7fffff,a
        move a1,r1
 g_osc_end:
osc_end:
        move r1,y:(r6+$7)
        move    y:(r6+$2),y1
        move    y:(r6+$a),x1
        move    y:(r6+$9),x0
        do      #$20,env_end
        move    x:(r4)+,y0
        mpysu   y0,x0,a
        dmacss  y0,x1,a
        mpysu   y1,x0,b
        dmacss  y1,x1,b
        move    a,y:(r7)+
        move    b1,x1
        move    b0,x0
env_end:
        move    x1,y:(r6+$a)
        move    x0,y:(r6+$9)
        rts
