; NFX-SV: state-variable filter (uSVF) on the previous track, AD envelope, VCA.
; Generated by the NFX generators in a custom-firmware project, where this exact
; code has run on hardware; the kit copy drops one input branch that only served
; a two-track machine the kit does not have. Edit here.
        include "sdk.inc"
VCA_SLEW equ 190218                   ; VCA gain slew per sample: full scale / 44.1 (1 ms)
        org p:SDK_BANK
machine_init:
        clr a
        move a,y:(r6+$9)
        move a,y:(r6+$a)
        move a,y:(r6+$b)
        move a,y:(r6+$c)
        move a,y:(r6+$d)
        move a,y:(r6+$e)
        move a,y:(r6+$f)
        move a,y:(r6+$10)
        move a,y:(r6+$11)
        move a,y:(r6+$12)
        move a,y:(r6+$13)
        move a,y:(r6+$14)
        move a,y:(r6+$15)
        rts
machine_update:
; Every trig discharges the envelope capacitor; audio integrators remain intact.
        clr a
        move a,y:(r6+$f)
        move a,y:(r6+$13)
        move #>1,a
        move a1,y:(r6+$e)
        move y:(r6+$11),a
        add #1,a
        move a1,y:(r6+$11)
        move y:(r6+$8),a              ; (re)open the gate: N samples (unused unless N >= 2)
        move a1,y:(r6+$15)
        rts
machine_render:
        move y:$142,a
        tst a
        jeq silent
; ---- Classify: envelope stage 0/1/2 only; active stages need base in clamp range.
        move y:(r6+$e),b
        tst b
        jeq ev_idle
        cmp #2,b
        jgt ev_idle
        tst b
        jlt ev_idle
        move y:(r6+$1),a
        cmp #2097,a
        jlt ev_idle
        cmp #>$480000,a
        jgt ev_idle
; ---- Block-rate envelope (v11): one exact 32-sample step per block.
; e = 1 - (1 - k)^32 from the per-sample coefficient k (five rounds of
; e <- 2e - e^2). Attack charges toward 2x full scale and peaks at full scale
; (decay from the next block); decay snaps to zero at or below 128 LSB.
        move #>$7fffff,y1
        move y:(r6+$f),y0             ; level
        cmp #1,b
        jne ev_decay
        move y:(r6+$5),a              ; ATK: mantissa, bit 23 = 2^-31 scale
        tst a
        jge ev_attack_k
        and #>$7fffff,a
        move a1,a
        asr #8,a,a                    ; k = mantissa * 2^-31
 ev_attack_k:
        jsr ev_pow32
        tfr y1,b
        sub y0,b
        move b1,x1                    ; Q-1 - level
        move y0,a
        move y:(r6+$13),a0
        mac x0,x1,a                   ; level += e (2 (Q-1) - level)
        mac x0,y1,a
        tfr y1,b
        cmp b,a
        jlt ev_store                  ; still charging
        move y1,a                     ; peak: full scale, decay from the next block
        move #>2,b
        move b1,y:(r6+$e)
        move y:(r6+$12),b
        add #1,b
        move b1,y:(r6+$12)
        jmp ev_store
 ev_decay:
        move y:(r6+$6),a              ; DEC coefficient
        jsr ev_pow32
        move y0,a
        move y:(r6+$13),a0
        mac -x0,y0,a                  ; level -= e level
        cmp #128,a
        jgt ev_store
        clr a                         ; snap to zero: idle
        move a,y:(r6+$e)
 ev_store:
        move a1,y:(r6+$f)
        move a0,y:(r6+$13)
; ---- dt ramps linearly to clamp(base + depth*level_end, 2097, $480000).
        move y:(r6+$4),x0             ; depth
        move x0,a
        tst a
        jeq ev_depth_zero
        move y:(r6+$f),y0
        move y:(r6+$1),x1
        mpy x0,y0,a
        add x1,a
        move #2097,y1
        cmp y1,a
        tlt y1,a
        move #>$480000,b
        cmp b,a
        tgt b,a
        move a1,a                     ; dt1
        move y:(r6+$10),b             ; dt0: the previous block's end value
        move b1,n0
        sub b,a
        tst a                         ; ddt = (dt1 - dt0) / 32, toward zero
        jge ev_step_up
        neg a
        asr #5,a,a
        move a1,a
        neg a
        jmp ev_step_done
 ev_step_up:
        asr #5,a,a
        move a1,a
 ev_step_done:
        move a1,x:$0
        asl #5,a,a
        add b,a
        move a1,y:(r6+$10)            ; dt_end = dt0 + 32 ddt
        move #1,n5                    ; per-sample dt ramp
        jmp filter_setup
; A = k (48-bit, 1.0 = 2^47) -> X0 = 1 - (1 - k)^32 (limited, truncated).
 ev_pow32:
        do #5,ev_pow32_end
        move a,x0
        asl a
        mac -x0,x0,a                  ; e <- 2e - e^2
 ev_pow32_end:
        move a,x0
        rts
 ev_idle:                            ; idle: dt = base, unclamped
 ev_depth_zero:                      ; clamp(base + 0) = base
        move y:(r6+$1),n0
        move n0,y:(r6+$10)
        move #0,n5
 filter_setup:
; ---- Pass 3: filter. Load state/coefficients into registers.
        move y:$140,a
        eor #$20,a
        move a1,r0
sv_in_ready:
        move y:(r6+$9),r1
        move y:(r6+$9),y0
        move y:(r6+$a),r2
        move y:(r6+$b),r3
        move y:(r6+$c),r5
        move y:(r6+$2),n1
        move y:(r6+$7),n6
        move #>$1fff,n3
        move #>$280,n4            ; tanh table, internal X
        move y:(r6+$3),a
        tst a
        jlt f_mode_high
        move a1,n2
        move n5,b
        tst b
        jne filt_lpbp_env
        jmp filt_lpbp_const
 f_mode_high:
        and #$7fffff,a
        move a1,a
        move a1,n2
        cmp #$7fffff,a
        jeq f_mode_hp
        move n5,b
        tst b
        jne filt_bphp_env
        jmp filt_bphp_const
 f_mode_hp:
        move n5,b
        tst b
        jne filt_hp_env
        jmp filt_hp_const
 filt_lpbp_const:
        move n6,x0                    ; the next sample's gain (v12)
        do #32,filt_lpbp_const_end
        move y:(r0)+,y1
        mpy x0,y1,a     n1,x0
        move a1,x1
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n1,x0
        move a0,r5
        move a,r2
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n2,x0
        move a0,r5
        mpy x0,y0,a     a,y1
        mac -x0,y1,a    y1,b
        add b,a         y1,r2
        asl #5,a,a
        move n6,x0                    ; the next sample's gain (v12)
        move a,y:(r7)+
 filt_lpbp_const_end:
        jmp filter_done
 filt_lpbp_env:
        move x:$0,x0                  ; the next sample's ddt (v12)
        do #32,filt_lpbp_env_end
        move n0,a
        add x0,a        y:(r0)+,y1
        move n6,x0
        move a1,n0                    ; dt += ddt
        mpy x0,y1,a     n1,x0
        move a1,x1
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n1,x0
        move a0,r5
        move a,r2
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n2,x0
        move a0,r5
        mpy x0,y0,a     a,y1
        mac -x0,y1,a    y1,b
        add b,a         y1,r2
        asl #5,a,a
        move x:$0,x0                  ; the next sample's ddt (v12)
        move a,y:(r7)+
 filt_lpbp_env_end:
        jmp filter_done
 filt_bphp_const:
        move n6,x0                    ; the next sample's gain (v12)
        do #32,filt_bphp_const_end
        move y:(r0)+,y1
        mpy x0,y1,a     n1,x0
        move a1,x1
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n1,x0
        move a0,r5
        move a,r2
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n2,x0
        move a0,r5
        mpy -x0,y0,a    a,r2
        move r6,y1
        mac x0,y1,a     y0,b
        add b,a
        asl #5,a,a
        move n6,x0                    ; the next sample's gain (v12)
        move a,y:(r7)+
 filt_bphp_const_end:
        jmp filter_done
 filt_bphp_env:
        move x:$0,x0                  ; the next sample's ddt (v12)
        do #32,filt_bphp_env_end
        move n0,a
        add x0,a        y:(r0)+,y1
        move n6,x0
        move a1,n0                    ; dt += ddt
        mpy x0,y1,a     n1,x0
        move a1,x1
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n1,x0
        move a0,r5
        move a,r2
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n2,x0
        move a0,r5
        mpy -x0,y0,a    a,r2
        move r6,y1
        mac x0,y1,a     y0,b
        add b,a
        asl #5,a,a
        move x:$0,x0                  ; the next sample's ddt (v12)
        move a,y:(r7)+
 filt_bphp_env_end:
        jmp filter_done
 filt_hp_const:
        move n6,x0                    ; the next sample's gain (v12)
        do #32,filt_hp_const_end
        move y:(r0)+,y1
        mpy x0,y1,a     n1,x0
        move a1,x1
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n1,x0
        move a0,r5
        move a,r2
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a
        move a0,r5
        move a,r2
        move r6,a
        asl #5,a,a
        move n6,x0                    ; the next sample's gain (v12)
        move a,y:(r7)+
 filt_hp_const_end:
        jmp filter_done
 filt_hp_env:
        move x:$0,x0                  ; the next sample's ddt (v12)
        do #32,filt_hp_env_end
        move n0,a
        add x0,a        y:(r0)+,y1
        move n6,x0
        move a1,n0                    ; dt += ddt
        mpy x0,y1,a     n1,x0
        move a1,x1
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a         n1,x0
        move a0,r5
        move a,r2
        mpy -x0,y0,a    r2,y1
        add x1,a
        sub y1,a        n0,x0
        move a,y1
        mpy x0,y1,a     r1,b
        asl a           r3,b0
        add b,a         y1,r6
        move n3,x0                    ; mask (v12: fills the slot)
        move a0,r3
        abs a           a2,n7
        asl #2,a,a
        move a,y1                     ; |4 bp|, limited
        mpy y1,#13,a                  ; index (A1)
        tfr y1,b
        and x0,b        a1,r4
        asl #10,b,b                   ; interpolation fraction, Q23
        move (r4)+n4
        move x:(r4)+,x0 b,y0          ; T[i]
        move x:(r4),y1                ; T[i+1]
        mpy y0,y1,a
        mac -y0,x0,a    x0,b
        add b,a         n7,b
        asr #5,a,a                    ; (K/2) tanh = table / 32
        move n0,x0                    ; dt (v12: fills the slot)
        tst b           a1,a
        neg a ifmi
        move a1,y0
        mpy x0,y0,a     y0,r1
        asl a           r2,b
        move r5,b0
        add b,a
        move a0,r5
        move a,r2
        move r6,a
        asl #5,a,a
        move x:$0,x0                  ; the next sample's ddt (v12)
        move a,y:(r7)+
 filt_hp_env_end:
        jmp filter_done
 filter_done:
        move y:$142,a                 ; R6 was the HP register: recompute state base
        lsl #6,a
        add #>$800,a
        move a1,r4
        nop
        move r1,y:(r4+$9)
        move r2,y:(r4+$a)
        move r3,y:(r4+$b)
        move r5,y:(r4+$c)
        move r6,y:(r4+$d)
; ---- Pass 4: VCA, one linear gain ramp per block (v10). R4 = state base.
VCA_STEP32 equ 6086976               ; 32 x VCA_SLEW: full scale in 1 ms, per block
; Target: the envelope level at the block end (+8 = 1), or for the gate (+8 >= 2)
; full scale while more than half a block of the gate count (+15) remains (the
; count drops by 32 per block). The change toward it is clamped to 32 slew steps
; (full scale in 1 ms) and spread as dg per sample (toward zero, so the ramp
; never overshoots); the block-end gain (+14) snaps to the target within 32 LSB.
; A block held at full scale skips the multiply: exact unity.
 vca_pass:
        move y:(r4+$8),a
        tst a
        jeq vca_off
        cmp #1,a
        jeq vca_env
        move y:(r4+$15),a             ; gate: samples still open
        clr b
        move #>$7fffff,y1
        cmp #16,a
        tgt y1,b                      ; open while more than half a block remains
        move #>32,x0
        sub x0,a
        tst a
        jge vca_count
        clr a
 vca_count:
        move a1,y:(r4+$15)
        tfr b,a
        jmp vca_target
 vca_env:
        move y:(r4+$f),a              ; envelope level at the block end
 vca_target:
        move a,y1                     ; target T
        move y:(r4+$14),b             ; gain g at the block start
        sub b,a
        move #>VCA_STEP32,x1
        cmp x1,a
        tgt x1,a
        move #>-VCA_STEP32,x1
        cmp x1,a
        tlt x1,a                      ; d = clamp(T - g, +-32 slew steps)
        tst a
        jge vca_up
        neg a
        asr #5,a,a
        move a1,a
        neg a
        jmp vca_step
 vca_up:
        asr #5,a,a
        move a1,a
 vca_step:
        move a1,x1                    ; dg = d/32, toward zero
        asl #5,a,a
        add b,a                       ; g + 32 dg
        move a1,x0
        move y1,a
        sub x0,a
        abs a
        cmp #32,a
        move x0,a
        tlt y1,a                      ; within 32 LSB of the target: snap to it
        move a1,y:(r4+$14)
        move x1,a
        tst a
        jne vca_ramp
        move #>$7fffff,x0
        cmp x0,b
        jeq vca_off                   ; held at full scale: exact unity
 vca_ramp:
        move y:$140,r5                ; output bank, linear (no reliance on M7 wrap)
        do #32,vca_end
        add x1,b        y:(r5),y0
        move b1,x0
        mpysu y0,x0,a                 ; y * g (unsigned gain)
        move a,y:(r5)+
 vca_end:
 vca_off:
        rts
silent:
        clr a
        do #32,silent_done
        move a,y:(r7)+
silent_done:
        rts
