#!/usr/bin/env python3
"""Generate gain.inc: NFX-4P's GAIN table, gain^4 / 4 in Q23 (uLADR's drive with
the input / 16), 65 even-knob entries that ladder_control interpolates.

    python3 generate_gain.py           # rewrite gain.inc
    python3 generate_gain.py --check   # fail if gain.inc is stale
"""
import argparse
from pathlib import Path

Q = 1 << 23
HERE = Path(__file__).resolve().parent


def gain(k):
    return round(Q * (k / 127) ** 4 / 4)


def content():
    return '| GENERATED by generate_gain.py: GAIN -> gain^4/4, Q23, knobs 0, 2, .. 126, 127.\n' + \
        ''.join(f'        .long {gain(min(127, 2 * i))}\n' for i in range(65))


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    path = HERE / 'gain.inc'
    if a.check:
        if path.read_text() != content():
            raise SystemExit('gain.inc is stale: run generate_gain.py')
    else:
        path.write_text(content())
